export const PROBLEM_CUSTOM_INPUT_EVALUATE_REQUEST = 'PROBLEM_CUSTOM_INPUT_EVALUATE_REQUEST';
export const PROBLEM_CUSTOM_INPUT_EVALUATE_SUCCESS = 'PROBLEM_CUSTOM_INPUT_EVALUATE_SUCCESS';
export const PROBLEM_CUSTOM_INPUT_EVALUATE_FAIL = 'PROBLEM_CUSTOM_INPUT_EVALUATE_FAIL';

export const PROBLEM_SUBMISSION_EVALUATE_REQUEST = 'PROBLEM_SUBMISSION_EVALUATE_REQUEST';
export const PROBLEM_SUBMISSION_EVALUATE_SUCCESS = 'PROBLEM_SUBMISSION_EVALUATE_SUCCESS';
export const PROBLEM_SUBMISSION_EVALUATE_FAIL = 'PROBLEM_SUBMISSION_EVALUATE_FAIL';