export const PROBLEM_TITLE_CHANGE = 'PROBLEM_TITLE_CHANGE'

export const PROBLEM_DESCRIPTION_CHANGE = 'PROBLEM_DESCRIPTION_CHANGE'

export const PROBLEM_DIFFICULTY_CHANGE = 'PROBLEM_DIFFICULTY_CHANGE'

export const PROBLEM_EDITORIAL_CHANGE = 'PROBLEM_EDITORIAL_CHANGE'
export const PROBLEM_DEFAULT_TEMPLATE_CHANGE = 'PROBLEM_DEFAULT_TEMPLATE_CHANGE'
export const PROBLEM_SOLUTION_CHANGE = 'PROBLEM_SOLUTION_CHANGE'
export const PROBLEM_TESTCASES_ADD_ONE = 'PROBLEM_TESTCASES_ADD_ONE'



export const PROBLEM_SUBMIT_REQUEST = 'PROBLEM_SUBMIT_REQUEST'
export const PROBLEM_SUBMIT_SUCCESS = 'PROBLEM_SUBMIT_SUCCESS'
export const PROBLEM_SUBMIT_FAIL = 'PROBLEM_SUBMIT_FAIL'
