export const PROBLEM_DISCUSSION_SUBMIT_REQUEST = 'PROBLEM_DISCUSSION_SUBMIT_REQUEST';
export const PROBLEM_DISCUSSION_SUBMIT_SUCCESS = 'PROBLEM_DISCUSSION_SUBMIT_SUCCESS';
export const PROBLEM_DISCUSSION_SUBMIT_FAIL = 'PROBLEM_DISCUSSION_SUBMIT_FAIL';

export const PROBLEM_DISCUSSIONS_GET_ALL_REQUEST = 'PROBLEM_DISCUSSIONS_GET_ALL_REQUEST';
export const PROBLEM_DISCUSSIONS_GET_ALL_SUCCESS = 'PROBLEM_DISCUSSIONS_GET_ALL_SUCCESS';
export const PROBLEM_DISCUSSIONS_GET_ALL_FAIL = 'PROBLEM_DISCUSSIONS_GET_ALL_FAIL';

export const PROBLEM_DISCUSSION_GET_REQUEST = 'PROBLEM_DISCUSSION_GET_REQUEST';
export const PROBLEM_DISCUSSION_GET_SUCCESS = 'PROBLEM_DISCUSSION_GET_SUCCESS';
export const PROBLEM_DISCUSSION_GET_FAIL = 'PROBLEM_DISCUSSION_GET_FAIL';