export const PROBLEM_GET_REQUEST = 'PROBLEM_GET_REQUEST'
export const PROBLEM_GET_SUCCESS = 'PROBLEM_GET_SUCCESS'
export const PROBLEM_GET_FAIL = 'PROBLEM_GET_FAIL'

export const PROBLEM_GET_ALL_REQUEST = 'PROBLEM_GET_ALL_REQUEST'
export const PROBLEM_GET_ALL_SUCCESS = 'PROBLEM_GET_ALL_SUCCESS'
export const PROBLEM_GET_ALL_FAIL = 'PROBLEM_GET_ALL_FAIL'